### ISSUE TITLE
Info missing from package.json

### ISSUE THREAD

**Issue by dosman711** [chef-partners/chef-hipchat-plugin#2]
You should flesh out the package.json file and include things like license, authors, description, etc. Even if you're not planning to publish to npm it is probably worth adding.

**Comment by jjasghar** [comment]
Great idea, it's still _technically_ pre-beta, but it'll be done ASAP.

**Comment by dosman711** [comment]
Yeah this is basically meant to act as a yellow sticky note on your monitor :smile: :memo:

**Comment by jjasghar** [comment]
Fixed via: https://github.com/chef-partners/chef-hipchat-plugin/pull/3
